Turn all C compilation warnings into errors
when running iic with --run

Suppress specific warnings to ensure a clean run:

In particular, add -Wno-switch-bool to suppress

error: switch condition has boolean value [-Werror,-Wswitch-bool]
   66 |     switch (x) {
      |     ^       ~

Better to replace by if-else, or cast to int.